### ISSUE TITLE
Getting the schema for a DynamicEmbeddedDocument via a top level endpoint

### ISSUE THREAD

**Issue by lawrlee** [wlanslovenija/django-tastypie-mongoengine#45]
With django-tastypie-mongoengine 0.4 and django-tastypie 0.9.14, I am trying to expose the schema for a resource created from a DynamicEmbeddedDocument. This used to work in 0.3+0.9.11 but now throws an `AttributeError: 'ListQuerySet' object has no attribute '_document'` error, presumably because the resource returns a ListQuerySet object that doesn't get converted to a MongoEngineListResource by the EmbeddedListField. 

For example, if I have the resources:

```
class EmbeddedFooResource(MongoEngineResource):
    ...
    class Meta:
        object_class = Foo #this is a DynamicEmbeddedDocument
        resource_name = 'foo'

class BarResource(MongoEngineResource):
    foo = EmbeddedListField('EmbeddedFooResource')
    ...
    class Meta:
        queryset = Bar.objects.all()
        resource_name = 'bar'
```

How would I get the schema for EmbeddedFooResource? `api/v1/foo/schema/` isn't working for me and `api/v1/bar/<_id>/1/foo/schema/` isn't possible. Thanks!
